name: aroki
description: "AROKI Flutter - Android compatible media and connector client"
publish_to: "none"

version: 2.0.38+51

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  html: ^0.15.4
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  provider: ^6.1.1
  video_player: ^2.8.2
  chewie: ^1.7.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
